version: '3'

services:
    postgres:
        image: postgres:14
        restart: always
        environment:
            POSTGRES_USER: next-admin
            POSTGRES_PASSWORD: next-admin
            POSTGRES_DB: next-admin
        ports:
            - 5432:5432
        volumes:
            - postgresql:/var/lib/postgresql
            - postgresql_data:/var/lib/postgresql/data

volumes:
    postgresql:
    postgresql_data:
