name: E2E tests
on:
  deployment_status:
jobs:
  run-e2e:
    if: github.event.deployment_status.state == 'success' && !contains(github.event.deployment_status.target_url, 'next-admin-docs')
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install && npx playwright install --with-deps
      - name: Run e2e tests
        run: yarn dotenv turbo test:e2e
        env:
          BASE_URL: ${{ github.event.deployment_status.target_url }}