name: E2E tests
on:
  pull_request:
    paths:
      - "packages/next-admin/**"
      - "apps/example/**"
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start docker-compose
        run: docker-compose up -d
      - name: Get cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install && npx playwright install --with-deps
      - name: Build packages
        run: yarn build
      - name: Fill database
        run: yarn database
      - name: Start server
        run: yarn start:example &
      - name: Run tests
        run: yarn turbo test:e2e
