name: E2E tests
on:
  pull_request:
    paths:
      - "packages/next-admin/**"
      - "apps/example/**"
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start docker-compose
        run: docker-compose up -d
      - name: List files
        run: ls -la
