name: Release

on:
  push:
    branches:
      - develop
      - hotfix
      - main
      - v[0-9]+

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install

      - name: Link
        run: yarn lint

      - name: Create Release Pull Request
        if: github.ref == 'refs/heads/develop'
        uses: changesets/action@v1
        with:
          version: yarn changeset version
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release Pull Request or Publish (${{ github.ref_name }})
        if: github.ref == 'refs/heads/hotfix'
        uses: changesets/action@v1
        with:
          version: yarn changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        if: github.ref == 'refs/heads/main'
        uses: changesets/action@v1
        with:
          version: yarn changeset version
          publish: yarn publish-package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release Pull Request or Publish (${{ github.ref_name }})
        if: startsWith(github.ref, 'refs/tags/v')
        uses: changesets/action@v1
        with:
          version: yarn changeset version
          publish: yarn publish-package
          title: ${{github.ref_name}} — Version Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
